-- DDL

CREATE TABLE FLASHCARD
(
    ID         INTEGER PRIMARY KEY,
    NAME  VARCHAR(100),
    MEAN   VARCHAR(100),
    LINKIMG  VARCHAR(100),
    LINKAUDIO   VARCHAR(100),
    TIMEWAIT     DOUBLE,
);

COMMIT;